// 120. Crear la interfaz para el usuario usar paste as jason copiarla de postman

// Generated by https://quicktype.io

export interface User {
  id:               number;
  user:             string;
  email:            string;
}
